#!/bin/bash

sourcedir=/tmp/src

set -e

source ${HTTPD_CONTAINER_SCRIPTS_PATH}/common.sh

echo "---> Enabling s2i support in httpd24 image"

config_s2i

echo "---> Converting markdown to HTML"
for f in $(find $sourcedir -name *.md -type f); do
  title="$(grep -m1 '^#' $f | sed -e 's/^#* *//g')"
  sed -i -E -e 's/\[([^]]*)\]\(([^)]*)\.md\)/[\1](\2.html)/g' $f
  pandoc \
    $PANDOC_OPTS \
    -f markdown \
    -t html5 \
    --metadata title="$title" \
    -V title:"" \
    -s $f \
    -o $(dirname $f)/$(basename -s .md $f).html
  rm $f
done

echo "---> Installing application source"
cp -af /tmp/src/. ./

# Fix source directory permissions
fix-permissions ./

process_extending_files ${HTTPD_APP_ROOT}/src/httpd-post-assemble/ ${HTTPD_CONTAINER_SCRIPTS_PATH}/post-assemble/

# Fix source directory permissions
fix-permissions ./
